login:
  musicbrainz_enabled:
    default: false
    client: true
  musicbrainz_client_id: ''
  musicbrainz_client_secret: ''
  musicbrainz_site_url: 'https://musicbrainz.org'
  musicbrainz_authorize_url: '/oauth2/authorize'
  musicbrainz_token_url: '/oauth2/token'
  musicbrainz_user_info_url: '/oauth2/userinfo'
  musicbrainz_email_verified: true
  musicbrainz_send_auth_header: true
  musicbrainz_button_title:
    default: 'with MusicBrainz'
    client: true
