login:
  oauth2_enabled:
    default: false
    client: true
  oauth2_client_id: ''
  oauth2_client_secret: ''
  oauth2_authorize_url: 'https://musicbrainz.org/oauth2/authorize'
  oauth2_token_url: 'https://musicbrainz.org/oauth2/token'
  oauth2_user_json_url: 'https://musicbrainz.org/oauth2/userinfo'
  oauth2_email_verified: true
  oauth2_send_auth_header: true
  oauth2_button_title:
    default: 'with MusicBrainz'
    client: true
